### ISSUE TITLE
问题真的有点多

### ISSUE THREAD

**Issue by Spittingwhale** [SK-Keith/Fix#4]
登陆不进去，
少文件
![WeChat Screenshot_20190828211739](https://user-images.githubusercontent.com/46148722/63859239-8e0fd800-c9d9-11e9-82a7-f3b6e27a1d86.png)

**Comment by Spittingwhale** [comment]
多谢指教，正在慢慢解决和优化项目存在的问题发自我的华为手机-------- 原始邮件 --------发件人： SK-Keith <notifications@github.com>日期： 2019年9月8日周日 13:46收件人： SK-Keith/Fix <Fix@noreply.github.com>抄送： Spittingwhale <changzj163@163.com>, Author <author@noreply.github.com>主    题： Re: [SK-Keith/Fix] 问题真的有点多 (#4)Closed #4.

**Comment by SK-Keith** [comment]
您好，请问下是哪里遇到问题吗，你可以加下我的qq(2690399241)进行交流。



------------------ 原始邮件 ------------------
发件人: "Spittingwhale"<notifications@github.com>; 
发送时间: 2019年9月8日(星期天) 晚上9:26
收件人: "SK-Keith/Fix"<Fix@noreply.github.com>; 
抄送: "Keith"<2690399241@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [SK-Keith/Fix] 问题真的有点多 (#4)



多谢指教，正在慢慢解决和优化项目存在的问题发自我的华为手机-------- 原始邮件 --------发件人： SK-Keith <notifications@github.com>日期： 2019年9月8日周日 13:46收件人： SK-Keith/Fix <Fix@noreply.github.com>抄送： Spittingwhale <changzj163@163.com>, Author <author@noreply.github.com>主    题： Re: [SK-Keith/Fix] 问题真的有点多 (#4)Closed #4.
